### ISSUE TITLE
Can't open FILENAME for reading error if file name contains non-ASCII chars

### ISSUE THREAD

**Issue by dehghani-mehdi** [garyzyg/mozjpeg-windows#2]
Hi,

Any chance to build mozjpeg to support non-ASCII chars in file name?

**Comment by garyzyg** [comment]
Hi

1. Are you saying to feed like cjpeg-static.exe with file name containing non-ASCII characters?
2. Or you want to rename cjpeg-static.exe with non-ASCII characters during build process?

Gary

**Comment by dehghani-mehdi** [comment]
The first one. e.g: `cjpeg-static.exe تست.jpg > output.jpg`

**Comment by garyzyg** [comment]
This project intends to build purely mozjpeg. mozilla/mozjpeg has its own CI build, and here is latest one. You can give it a try.
https://ci.appveyor.com/project/kornel/mozjpeg-4ekrx/builds/31067245/artifacts

**Comment by dehghani-mehdi** [comment]
Thanks, but I already tried that, actually because that build didn't support non-ASCII chars I tried your version. I'm wondering is there any way to change CI so the output support non-ASCII chars?

**Comment by garyzyg** [comment]
I think this requires source modification and you may need to contact the owner of mozilla/mozjpeg.
