### ISSUE TITLE
.png

### ISSUE THREAD

**Issue by ropucyka** [garyzyg/mozjpeg-windows#3]
Please add version with PNG support.
Version on appveyor autoremoved long time ago.

**Comment by garyzyg** [comment]
Latest commit is able to build mozjpeg with PNG support. If next release of mozjpeg comes out, I will try. Of course, it still depends on readiness from upstream. If you can't wait, just fork this project to get your own build.

**Comment by ropucyka** [comment]
Dude. Not all people is programmers. I just want to transcode some of my png's to mozjpeg. Just advanced user, no more. I can wait, yes. I'm waiter No1 in the world.

My respect for your work with these and all others binaries.

**Comment by garyzyg** [comment]
@ropucyka mozjpeg 4.0.1-rc2 is released officially. You may download official release there or my build here. They shall all support png.

**Comment by garyzyg** [comment]
Closed as [comment](https://github.com/garyzyg/mozjpeg-windows/issues/3#issuecomment-706013328).
